version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
       POSTGRES_PASSWORD: erasmus
       POSTGRES_USER: erasmus
       POSTGRES_DB: erasmus
    ports:
      - '5432:5432'
  erasmus:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - '8080:80'
  adminer:
    image: adminer